[0m14:13:00.578442 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f31eaccd2d0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f31ea005410>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f31ea007610>]}


============================== 14:13:00.581585 | 4e7ee84a-cdb9-4dff-8494-e9c861813e44 ==============================
[0m14:13:00.581585 [info ] [MainThread]: Running with dbt=1.9.8
[0m14:13:00.582187 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'debug': 'False', 'version_check': 'True', 'log_path': 'logs', 'profiles_dir': '/home/esteban/.dbt', 'fail_fast': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'None', 'quiet': 'False', 'no_print': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'static_parser': 'True', 'log_format': 'default', 'invocation_command': 'dbt init nasa', 'target_path': 'None', 'introspect': 'True', 'send_anonymous_usage_stats': 'True'}
[0m14:13:00.596152 [debug] [MainThread]: Starter project path: /home/esteban/Apps/anaconda3/envs/py311_spark/lib/python3.11/site-packages/dbt/include/starter_project
[0m14:13:00.600902 [info ] [MainThread]: 
Your new dbt project "nasa" was created!

For more information on how to configure the profiles.yml file,
please consult the dbt documentation here:

  https://docs.getdbt.com/docs/configure-your-profile

One more thing:

Need help? Don't hesitate to reach out to us via GitHub issues or on Slack:

  https://community.getdbt.com/

Happy modeling!

[0m14:13:00.601910 [info ] [MainThread]: Setting up your profile.
[0m14:14:14.846352 [debug] [MainThread]: Resource report: {"command_name": "init", "command_success": true, "command_wall_clock_time": 74.32919, "process_in_blocks": "80736", "process_kernel_time": 0.192783, "process_mem_max_rss": "110920", "process_out_blocks": "72", "process_user_time": 1.485742}
[0m14:14:14.847426 [debug] [MainThread]: Command `dbt init` succeeded at 14:14:14.847169 after 74.33 seconds
[0m14:14:14.848221 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f31ea0ee2d0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f31ee177710>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f31ee2b5e10>]}
[0m14:14:14.848938 [debug] [MainThread]: Flushing usage events
[0m14:14:16.098786 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m20:33:24.532808 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7990c12af690>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7990c13063d0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7990c1304fd0>]}


============================== 20:33:24.541110 | 255df099-8d16-482d-9d09-f690c3debfa2 ==============================
[0m20:33:24.541110 [info ] [MainThread]: Running with dbt=1.9.8
[0m20:33:24.541771 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'version_check': 'True', 'profiles_dir': '/home/esteban/UNAL/BigData/asignaciones/dbt/nasa/.dbt', 'log_path': 'logs', 'fail_fast': 'False', 'debug': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'None', 'quiet': 'False', 'no_print': 'None', 'log_format': 'default', 'invocation_command': 'dbt debug', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'static_parser': 'True', 'target_path': 'None', 'introspect': 'True', 'send_anonymous_usage_stats': 'True'}
[0m20:33:24.546070 [info ] [MainThread]: dbt version: 1.9.8
[0m20:33:24.546342 [info ] [MainThread]: python version: 3.11.10
[0m20:33:24.546588 [info ] [MainThread]: python path: /home/esteban/Apps/anaconda3/envs/py311_spark/bin/python3.11
[0m20:33:24.546912 [info ] [MainThread]: os info: Linux-6.14.0-24-generic-x86_64-with-glibc2.39
[0m20:33:24.627372 [info ] [MainThread]: Using profiles dir at /home/esteban/UNAL/BigData/asignaciones/dbt/nasa/.dbt
[0m20:33:24.627861 [info ] [MainThread]: Using profiles.yml file at /home/esteban/UNAL/BigData/asignaciones/dbt/nasa/.dbt/profiles.yml
[0m20:33:24.628188 [info ] [MainThread]: Using dbt_project.yml file at /home/esteban/UNAL/BigData/asignaciones/dbt/dbt_project.yml
[0m20:33:24.630110 [info ] [MainThread]: adapter type: duckdb
[0m20:33:24.630517 [info ] [MainThread]: adapter version: 1.9.3
[0m20:33:24.630864 [info ] [MainThread]: Configuration:
[0m20:33:24.631173 [info ] [MainThread]:   profiles.yml file [[32mOK found and valid[0m]
[0m20:33:24.631455 [info ] [MainThread]:   dbt_project.yml file [[31mERROR not found[0m]
[0m20:33:24.631724 [info ] [MainThread]: Required dependencies:
[0m20:33:24.632024 [debug] [MainThread]: Executing "git --help"
[0m20:33:24.633687 [debug] [MainThread]: STDOUT: "b"usage: git [-v | --version] [-h | --help] [-C <path>] [-c <name>=<value>]\n           [--exec-path[=<path>]] [--html-path] [--man-path] [--info-path]\n           [-p | --paginate | -P | --no-pager] [--no-replace-objects] [--bare]\n           [--git-dir=<path>] [--work-tree=<path>] [--namespace=<name>]\n           [--config-env=<name>=<envvar>] <command> [<args>]\n\nThese are common Git commands used in various situations:\n\nstart a working area (see also: git help tutorial)\n   clone     Clone a repository into a new directory\n   init      Create an empty Git repository or reinitialize an existing one\n\nwork on the current change (see also: git help everyday)\n   add       Add file contents to the index\n   mv        Move or rename a file, a directory, or a symlink\n   restore   Restore working tree files\n   rm        Remove files from the working tree and from the index\n\nexamine the history and state (see also: git help revisions)\n   bisect    Use binary search to find the commit that introduced a bug\n   diff      Show changes between commits, commit and working tree, etc\n   grep      Print lines matching a pattern\n   log       Show commit logs\n   show      Show various types of objects\n   status    Show the working tree status\n\ngrow, mark and tweak your common history\n   branch    List, create, or delete branches\n   commit    Record changes to the repository\n   merge     Join two or more development histories together\n   rebase    Reapply commits on top of another base tip\n   reset     Reset current HEAD to the specified state\n   switch    Switch branches\n   tag       Create, list, delete or verify a tag object signed with GPG\n\ncollaborate (see also: git help workflows)\n   fetch     Download objects and refs from another repository\n   pull      Fetch from and integrate with another repository or a local branch\n   push      Update remote refs along with associated objects\n\n'git help -a' and 'git help -g' list available subcommands and some\nconcept guides. See 'git help <command>' or 'git help <concept>'\nto read about a specific subcommand or concept.\nSee 'git help git' for an overview of the system.\n""
[0m20:33:24.634207 [debug] [MainThread]: STDERR: "b''"
[0m20:33:24.634554 [info ] [MainThread]:  - git [[32mOK found[0m]

[0m20:33:24.635003 [info ] [MainThread]: Connection:
[0m20:33:24.635534 [info ] [MainThread]:   database: unal
[0m20:33:24.635986 [info ] [MainThread]:   schema: main
[0m20:33:24.636444 [info ] [MainThread]:   path: /home/esteban/UNAL/BigData/asignaciones/dbt/database/unal.db
[0m20:33:24.636879 [info ] [MainThread]:   config_options: None
[0m20:33:24.637324 [info ] [MainThread]:   extensions: ['httpfs', 'parquet']
[0m20:33:24.637776 [info ] [MainThread]:   settings: {}
[0m20:33:24.638234 [info ] [MainThread]:   external_root: .
[0m20:33:24.638798 [info ] [MainThread]:   use_credential_provider: None
[0m20:33:24.639259 [info ] [MainThread]:   attach: None
[0m20:33:24.639786 [info ] [MainThread]:   filesystems: None
[0m20:33:24.640233 [info ] [MainThread]:   remote: None
[0m20:33:24.640717 [info ] [MainThread]:   plugins: None
[0m20:33:24.641132 [info ] [MainThread]:   disable_transactions: False
[0m20:33:24.641707 [info ] [MainThread]: Registered adapter: duckdb=1.9.3
[0m20:33:24.697302 [debug] [MainThread]: Acquiring new duckdb connection 'debug'
[0m20:33:24.710730 [debug] [MainThread]: Using duckdb connection "debug"
[0m20:33:24.711057 [debug] [MainThread]: On debug: select 1 as id
[0m20:33:24.711297 [debug] [MainThread]: Opening a new connection, currently in state init
[0m20:33:24.776301 [debug] [MainThread]: SQL status: OK in 0.065 seconds
[0m20:33:24.777157 [debug] [MainThread]: On debug: Close
[0m20:33:24.777529 [info ] [MainThread]:   Connection test: [[32mOK connection ok[0m]

[0m20:33:24.777848 [info ] [MainThread]: [31m1 check failed:[0m
[0m20:33:24.778097 [info ] [MainThread]: Project loading failed for the following reason:
 project path </home/esteban/UNAL/BigData/asignaciones/dbt/dbt_project.yml> not found

[0m20:33:24.778698 [debug] [MainThread]: Resource report: {"command_name": "debug", "command_success": false, "command_wall_clock_time": 0.28058532, "process_in_blocks": "8", "process_kernel_time": 0.118718, "process_mem_max_rss": "143360", "process_out_blocks": "24", "process_user_time": 1.363766}
[0m20:33:24.779098 [debug] [MainThread]: Command `dbt debug` failed at 20:33:24.779017 after 0.28 seconds
[0m20:33:24.779403 [debug] [MainThread]: Connection 'debug' was properly closed.
[0m20:33:24.779709 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7990c547b890>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7990c1305050>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7990c11ee7d0>]}
[0m20:33:24.780060 [debug] [MainThread]: Flushing usage events
[0m18:22:44.043696 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7d55a02fe790>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7d55a02fe710>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7d55a02fdad0>]}


============================== 18:22:44.047566 | 5c2a114a-256f-4822-9995-a5b7cffaab04 ==============================
[0m18:22:44.047566 [info ] [MainThread]: Running with dbt=1.9.8
[0m18:22:44.048326 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': '/home/esteban/UNAL/BigData/asignaciones/dbt/nasa/.dbt', 'fail_fast': 'False', 'version_check': 'True', 'log_path': 'logs', 'warn_error': 'None', 'debug': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'None', 'log_format': 'default', 'invocation_command': 'dbt deps', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'static_parser': 'True', 'target_path': 'None', 'introspect': 'True', 'send_anonymous_usage_stats': 'True'}
[0m18:22:44.049021 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /home/esteban/UNAL/BigData/asignaciones/dbt/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m18:22:44.049990 [debug] [MainThread]: Resource report: {"command_name": "deps", "command_success": false, "command_wall_clock_time": 0.047508076, "process_in_blocks": "8", "process_kernel_time": 0.081981, "process_mem_max_rss": "97080", "process_out_blocks": "8", "process_user_time": 1.000772}
[0m18:22:44.050500 [debug] [MainThread]: Command `dbt deps` failed at 18:22:44.050390 after 0.05 seconds
[0m18:22:44.050889 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7d55a02feb10>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7d55a447b7d0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7d55a02a3a50>]}
[0m18:22:44.051282 [debug] [MainThread]: Flushing usage events
[0m18:22:45.301802 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m18:22:46.505840 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x78312eb84190>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x78312edd17d0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x78312ebe5710>]}


============================== 18:22:46.507926 | 87ec3454-3035-4a45-8a4c-ff2a891c960f ==============================
[0m18:22:46.507926 [info ] [MainThread]: Running with dbt=1.9.8
[0m18:22:46.508334 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'fail_fast': 'False', 'profiles_dir': '/home/esteban/UNAL/BigData/asignaciones/dbt/nasa/.dbt', 'log_path': 'logs', 'version_check': 'True', 'debug': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'None', 'quiet': 'False', 'no_print': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'invocation_command': 'dbt seed', 'introspect': 'True', 'static_parser': 'True', 'target_path': 'None', 'log_format': 'default', 'send_anonymous_usage_stats': 'True'}
[0m18:22:46.508718 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /home/esteban/UNAL/BigData/asignaciones/dbt/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m18:22:46.509395 [debug] [MainThread]: Resource report: {"command_name": "seed", "command_success": false, "command_wall_clock_time": 0.040767398, "process_in_blocks": "0", "process_kernel_time": 0.096533, "process_mem_max_rss": "97260", "process_out_blocks": "0", "process_user_time": 0.949407}
[0m18:22:46.509819 [debug] [MainThread]: Command `dbt seed` failed at 18:22:46.509734 after 0.04 seconds
[0m18:22:46.510151 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x78312eb84250>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x783132d77690>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x78312ebf3d50>]}
[0m18:22:46.510490 [debug] [MainThread]: Flushing usage events
[0m18:22:46.917446 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m18:22:48.156923 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fe6da70de10>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fe6da9ee710>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fe6da6b9a90>]}


============================== 18:22:48.159044 | 46328e61-20ea-4592-ae8e-8a6bd721d25e ==============================
[0m18:22:48.159044 [info ] [MainThread]: Running with dbt=1.9.8
[0m18:22:48.159510 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'version_check': 'True', 'profiles_dir': '/home/esteban/UNAL/BigData/asignaciones/dbt/nasa/.dbt', 'log_path': 'logs', 'debug': 'False', 'fail_fast': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'None', 'log_format': 'default', 'introspect': 'True', 'static_parser': 'True', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'target_path': 'None', 'invocation_command': 'dbt test', 'send_anonymous_usage_stats': 'True'}
[0m18:22:48.159943 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /home/esteban/UNAL/BigData/asignaciones/dbt/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m18:22:48.160676 [debug] [MainThread]: Resource report: {"command_name": "test", "command_success": false, "command_wall_clock_time": 0.04416868, "process_in_blocks": "0", "process_kernel_time": 0.091823, "process_mem_max_rss": "97040", "process_out_blocks": "8", "process_user_time": 0.985103}
[0m18:22:48.161115 [debug] [MainThread]: Command `dbt test` failed at 18:22:48.161018 after 0.04 seconds
[0m18:22:48.161443 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fe6de87b7d0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fe6da70ee90>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fe6da6b8310>]}
[0m18:22:48.161794 [debug] [MainThread]: Flushing usage events
[0m18:22:48.564492 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m18:22:49.782216 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7deeb3aac510>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7deeb3ae8310>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7deeb3ae8550>]}


============================== 18:22:49.784424 | f1a497fd-3601-4d44-8523-47c431eef44d ==============================
[0m18:22:49.784424 [info ] [MainThread]: Running with dbt=1.9.8
[0m18:22:49.784966 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': '/home/esteban/UNAL/BigData/asignaciones/dbt/nasa/.dbt', 'version_check': 'True', 'debug': 'False', 'log_path': 'logs', 'warn_error': 'None', 'fail_fast': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'False', 'quiet': 'False', 'no_print': 'None', 'log_format': 'default', 'introspect': 'True', 'invocation_command': 'dbt run', 'static_parser': 'True', 'target_path': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'send_anonymous_usage_stats': 'True'}
[0m18:22:49.785389 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /home/esteban/UNAL/BigData/asignaciones/dbt/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m18:22:49.786100 [debug] [MainThread]: Resource report: {"command_name": "run", "command_success": false, "command_wall_clock_time": 0.043688554, "process_in_blocks": "0", "process_kernel_time": 0.106576, "process_mem_max_rss": "97500", "process_out_blocks": "0", "process_user_time": 0.955205}
[0m18:22:49.786493 [debug] [MainThread]: Command `dbt run` failed at 18:22:49.786416 after 0.04 seconds
[0m18:22:49.786823 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7deeb3b15c90>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7deeb7c7b810>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7deeb3b0b6d0>]}
[0m18:22:49.787168 [debug] [MainThread]: Flushing usage events
[0m18:22:50.166413 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m18:22:51.391963 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fba18ca5750>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fba18d07d90>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fba1b227f90>]}


============================== 18:22:51.394052 | 2da5e48a-d3d5-4e91-a2ed-7f754a7dae4e ==============================
[0m18:22:51.394052 [info ] [MainThread]: Running with dbt=1.9.8
[0m18:22:51.394589 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': '/home/esteban/UNAL/BigData/asignaciones/dbt/nasa/.dbt', 'fail_fast': 'False', 'version_check': 'True', 'log_path': 'logs', 'warn_error': 'None', 'debug': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'introspect': 'True', 'static_parser': 'True', 'invocation_command': 'dbt docs generate', 'target_path': 'None', 'log_format': 'default', 'send_anonymous_usage_stats': 'True'}
[0m18:22:51.395019 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /home/esteban/UNAL/BigData/asignaciones/dbt/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m18:22:51.395690 [debug] [MainThread]: Resource report: {"command_name": "generate", "command_success": false, "command_wall_clock_time": 0.04346254, "process_in_blocks": "0", "process_kernel_time": 0.090855, "process_mem_max_rss": "96940", "process_out_blocks": "0", "process_user_time": 0.969461}
[0m18:22:51.396129 [debug] [MainThread]: Command `dbt docs generate` failed at 18:22:51.396047 after 0.04 seconds
[0m18:22:51.396460 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fba18d07d90>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fba18d07ed0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fba18ca3cd0>]}
[0m18:22:51.396862 [debug] [MainThread]: Flushing usage events
[0m18:22:51.757086 [debug] [MainThread]: An error was encountered while trying to flush usage events
